@file:Suppress("unused")

package org.tesserakt.diskordin.commands.integration

/**
 * Sets the level of compilation output generated by command module compiler
 */
enum class CompilerOutput {
    /**
     * Print all information about compilation process
     */
    Verbose,

    /**
     * Print only compilation summary at the end
     */
    Summary,

    /**
     * Do not print any info
     */
    Quiet
}