name: Build Diskordin

on: [push, pull_request, release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@2

      - name: Set up JDK 1.8
        uses: actions/setup-java@1
        with:
          version: 1.8

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Test if not release
        if: github.event_name != 'release'
        env:
          token: ${{secrets.discord_token}}
        run: ./gradlew test

      - name: Publish to Bintray if release
        if: github.event_name == 'release'
        env:
          bintray.user: ${{secrets.bintray_user}}
          bintray.key: ${{secrets.bintray_key}}
          diskordin.version: ${{github.ref}}
        run ./gradlew bintrayUpload -D$bintray.user -Dbintray.key -Ddiskordin.version
      
