name: Gradle CI

on: [push, pull_request]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.0.0
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
