name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [1.8, 11, 12]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          version: ${{matrix.jdk}}
      - name: Build and test
        env:
          jvm: ${{matrix.jdk}}
          token: ${{secrets.discord_token}}
        run: |
          chmod +x gradlew
          ./gradlew clean build
          ./gradlew check
