name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [1.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.jdk}}
      - name: Build and test
        env:
          jvm: ${{matrix.jdk}}
          token: ${{secrets.discord_token}}
          kotest.proptest.default.iteration.count: ${{secrets.test_depth}}
        run: |
          gradle --parallel test
      - name: Upload diskordin test results
        if: always()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: diskordin_test_report_${{github.run_id}}
          path: diskordin-base/build/reports/
      - name: Upload diskordin-commands test results
        if: always()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: diskordin_commands_test_report_${{github.run_id}}
          path: diskordin-commands/build/reports/
