name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [1.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          version: ${{matrix.jdk}}
      - name: Build and test
        env:
          jvm: ${{matrix.jdk}}
          token: ${{secrets.discord_token}}
          test_count: ${{secrets.test_depth}}
        run: |
          chmod +x gradlew
          ./gradlew clean build
          ./gradlew :check :diskordin-commands:check
      - name: Upload test results
        uses: actions/upload-artifact@v1.0.0
        with:
          name: diskordin_test_report_${{github.run_id}}
          path: build/reports/
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: diskordin_build_${{github.run_id}}
          path: build/libs/
